### ISSUE TITLE
We need utilities associated with password

### ISSUE THREAD

**Issue by nstarlike** [nstarlike/JavaUtils#5]
@BelleHan Do you have any idea of features? Feel free. :)

**Comment by nstarlike** [comment]
I think the following features would be good
* Creating a random password
* Encrypting a password
* Decrypting a password
* Checking a password whether or not it's safe

**Comment by BelleHan** [comment]
I agree with your idea.
Do we need this for member management module?

**Comment by nstarlike** [comment]
Yes, every system will need this. So, we can reuse this in every system.
I will make a draft class and make a pull request so that you can review it.
